name = "portfolio"

[[ d1_databases ]]
binding = "DB"
database_name = "portfolio"
database_id = ""
preview_database_id = "DB"

[[r2_buckets]]
binding = 'BUCKET'        # <~ valid JavaScript variable name
bucket_name = 'portfolio'

[vars]
ACCOUNT_ID = ""
AUTHOR_EMAIL = ""
BUCKET_KEY_ID = ""
BUCKET_NAME = ""
BUCKET_SECRET = ""
RECAPTCHA_SECRET = ""
RECAPTCHA_SITEKEY = ""
WEBMENTION_API_KEY = ""
RESEND_API_KEY = ""
MAPTILER_API_KEY = ""
