name = "portfolio"

[vars]
BUCKET_ENDPOINT = ""
BUCKET_KEY_ID = ""
BUCKET_NAME = ""
BUCKET_REGION = ""
BUCKET_SECRET = ""
TURSO_AUTH_TOKEN = ""
TURSO_DATABASE_URL = ""
WEBMENTION_API_KEY = ""
RESEND_API_KEY = ""
