name = "portfolio"

[[d1_databases]]
binding = "DB"
database_name = "portfolio"
database_id = ""
preview_database_id = "DB"

[[r2_buckets]]
binding = 'BUCKET'        # <~ valid JavaScript variable name
bucket_name = 'portfolio'

[vars]
ACCOUNT_ID = ""
BUCKET_KEY_ID = ""
BUCKET_NAME = ""
BUCKET_SECRET = ""
DATABASE_ID = ""
D1_TOKEN = ""
WEBMENTION_API_KEY = ""
RESEND_API_KEY = ""
RECAPTCHA_SITEKEY = ""
RECAPTCHA_SECRET = ""
MAPTILER_API_KEY = ""
