name = "portfolio"

kv_namespaces = [{ binding = "COMMENTS", id = "" }]

[[d1_databases]]
binding = "DB"
database_name = "portfolio"
database_id = ""
preview_database_id = "DB"

[vars]
AUTHOR_EMAIL = ""
MAPTILER_API_KEY = ""
TURNSTILE_SITE_KEY = ""
TURNSTILE_SECRET = ""
RESEND_API_KEY = ""
WEBMENTION_API_KEY = ""
