name = "portfolio"

[[ d1_databases ]]
binding = "DB"
database_name = "portfolio"
database_id = ""

[vars]
ACCOUNT_ID = ""
AUTHOR_EMAIL = ""
BUCKET_KEY_ID = ""
BUCKET_NAME = ""
BUCKET_SECRET = ""
RECAPTCHA_SECRET = ""
RECAPTCHA_SITEKEY = ""
WEBMENTION_API_KEY = ""
RESEND_API_KEY = ""
MAPTILER_API_KEY = ""
