name = "portfolio"
compatibility_flags = ["nodejs_als"]

kv_namespaces = [
    { binding = "COMMENTS", id = "a8b96ad55a6b4bcf9329ad26c294e181" },
]

[[d1_databases]]
binding = "DB"
database_name = "portfolio"
database_id = "6d4dbbba-aa9d-43bd-b982-5ab3447283b2"
preview_database_id = "DB"

[vars]
AUTHOR_EMAIL = ""
MAPTILER_API_KEY = ""
RECAPTCHA_SECRET = ""
RECAPTCHA_SITE_KEY = ""
RESEND_API_KEY = ""
WEBMENTION_API_KEY = ""
