name: ci

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Check for build and type issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun astro check
      - run: bun build
